# Generated by Django 3.1.2 on 2020-10-31 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Executive', 'executive'), ('Business', 'business'), ('Convalescence', 'executive')], default='Business', max_length=30)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('room_number', models.PositiveIntegerField()),
                ('room_status', models.CharField(blank=True, choices=[('Occupied', 'Occupied'), ('Free', 'Free'), ('Booked', 'Booked')], default=True, max_length=10)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('check_in_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField(default=1)),
                ('check_out_date', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room', to='reception.room')),
            ],
        ),
    ]
