# Generated by Django 3.1.2 on 2020-10-31 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
