# Generated by Django 3.1.2 on 2020-10-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_auto_20201031_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupant',
            name='phone',
            field=models.CharField(error_messages={'unique': 'This phone field must contain only numbers of eleven characters.'}, max_length=11),
        ),
    ]
