# Generated by Django 3.1.2 on 2020-11-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_auto_20201031_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupant',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
