# Generated by Django 3.1.2 on 2020-11-02 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_occupant_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupant',
            name='room',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room', to='reception.room'),
        ),
    ]
