# Generated by Django 3.1.2 on 2020-11-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0006_auto_20201102_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupant',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='occupant',
            name='room',
        ),
        migrations.CreateModel(
            name='OccupantPaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('Occupant', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room', to='reception.occupant')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room', to='reception.room')),
            ],
        ),
    ]
