# Generated by Django 3.1.2 on 2020-11-02 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0007_auto_20201102_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupant',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='occupant',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='occupant',
            name='username',
        ),
        migrations.AddField(
            model_name='occupantpaymentdetails',
            name='check_in_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupantpaymentdetails',
            name='check_out_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='occupantpaymentdetails',
            name='Occupant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='occupant', to='reception.occupant'),
        ),
    ]
